### ISSUE TITLE
Should we let the keyboard emit 'change' event with every input?

### ISSUE THREAD

**Issue by lcb931023** [HeliosInteractive/JS-OnScreen-Keyboard#1]
The word 'change' makes sense to be used for our effects on `<input>`, `<select>`, or `<textarea>`. However the behavior is inconsistent depending on which input method we use, and on which platform.

https://developer.mozilla.org/en-US/docs/Web/Events/change

> Different browsers do not always agree whether a change event should be fired for certain types of interaction. For example, keyboard navigation in <select> elements never fires a change event in Gecko until the user hits Enter or switches the focus away from the <select>

**Comment by adammcfadden** [comment]
A bit late to the party here, but this update was made [in this commit](https://github.com/HeliosInteractive/JS-OnScreen-Keyboard/commit/b9a52698f8f35c25a463b5a069d3c1976f28214d).

Adding the `input` and `change` events was specifically so that `v-model` would be able to work and pick up changes as they come in.
